const MAX_LEFT_PIXEL = 400;
const MARIO_KOOPA_PIX_DIFFERENCE = 6;
const HIGHEST_Y_POSITION = 460;
const ENEMY_KILL_SCORE = 300;
const ENEMY_TOPSPEED = 0.6;
const ENTITIES_ANIMATION_SPEED = 30;
const COIN_COLLECT_SCORE = 100;
